name: 'supplychain360'
version: '1.0.0'
config-version: 2

profile: 'supplychain360'

model-paths: ["supplychain360/models"]
analysis-paths: ["supplychain360/analyses"]
test-paths: ["supplychain360/tests"]
seed-paths: ["supplychain360/seeds"]
macro-paths: ["supplychain360/macros"]
snapshot-paths: ["supplychain360/snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"


models:
  supplychain360:
    staging:
      +schema: staging
      +materialized: table
    marts:
      +schema: marts
      +materialized: table