
-- Snowflake Database and Warehouse Setup for SupplyChain360

-- 1 Database
CREATE DATABASE IF NOT EXISTS SUPPLYCHAIN360_DB;

-- 2. Schemas
CREATE SCHEMA IF NOT EXISTS SUPPLYCHAIN360_DB.RAW;
CREATE SCHEMA IF NOT EXISTS SUPPLYCHAIN360_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS SUPPLYCHAIN360_DB.MARTS;

-- 3. Warehouse
CREATE WAREHOUSE IF NOT EXISTS SUPPLYCHAIN360_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;