-- Stage and Tables Setup for SupplyChain360 Snowflake Data Warehouse

-- Switch to project role
USE ROLE SUPPLYCHAIN360_ROLE;


-- 1. CREATE EXTERNAL STAGE
-- =====================================================
CREATE STAGE IF NOT EXISTS SUPPLYCHAIN360_DB.RAW.SUPPLYCHAIN360_S3_STAGE
URL = 's3://supplychain360-data-lake/raw/'
STORAGE_INTEGRATION = SUPPLYCHAIN360_S3_INTEGRATION;

-- Verify stage access
LIST @SUPPLYCHAIN360_DB.RAW.SUPPLYCHAIN360_S3_STAGE;

-- =====================================================
-- 2. CREATE RAW TABLES (VARIANT STRUCTURE)
-- =====================================================
-- Raw layer stores semi-structured data as-is

CREATE TABLE IF NOT EXISTS SUPPLYCHAIN360_DB.RAW.PRODUCTS (
    DATA VARIANT
);

CREATE TABLE IF NOT EXISTS SUPPLYCHAIN360_DB.RAW.STORE_LOCATIONS (
    DATA VARIANT
);

CREATE TABLE IF NOT EXISTS SUPPLYCHAIN360_DB.RAW.SHIPMENTS (
    DATA VARIANT
);

CREATE TABLE IF NOT EXISTS SUPPLYCHAIN360_DB.RAW.SALES (
    DATA VARIANT
);

CREATE TABLE IF NOT EXISTS SUPPLYCHAIN360_DB.RAW.SUPPLIERS (
    DATA VARIANT
);

CREATE TABLE IF NOT EXISTS SUPPLYCHAIN360_DB.RAW.INVENTORY (
    DATA VARIANT
);

CREATE TABLE IF NOT EXISTS SUPPLYCHAIN360_DB.RAW.WAREHOUSES (
    DATA VARIANT
);