version: 2

sources:
  - name: raw
    database: supplychain360_db
    schema: raw

    tables:
      - name: store_locations
      - name: products
      - name: shipments
      - name: sales
      - name: suppliers
      - name: inventory
      - name: warehouses


models:
  - name: stg_store_locations
    description: Staging table for store locations data.

  - name: stg_products
    description: Staging table for products data.

  - name: stg_shipments.
    description: Staging table for shipments data.

  - name: stg_sales_transaction
    description: Staging table for sales transaction data.

  - name: stg_suppliers
    description: Staging table for suppliers' data.

  - name: stg_inventory
    description: Staging table for inventory data.

  - name: stg_warehouses
    description: Staging table for warehouse data.