version: 2
models:

  - name: stg_store_locations
    description: Staging table for store locations data

  - name: stg_products
    description: Staging table for products data

  - name: stg_shipments
    description: Staging table for shipments data

# Adding stg_sales_transaction model with detailed column descriptions and tests
  - name: stg_sales_transaction
    description: Staging table for sales transaction data
    columns:
      - name: transaction_id
        description: The unique identifier for each sales transaction
        tests:
          - unique
          - not_null

      - name: quantity_sold
        description: The quantity of products sold in the transaction
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: unit_price
        description: The price per unit for the products sold.
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: sales_amount
        description: The total amount for the sales transaction
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"


  - name: stg_suppliers
    description: Staging table for suppliers' data

  - name: stg_inventory
    description: Staging table for inventory data

  - name: stg_warehouses
    description: Staging table for warehouse data