name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      - name: Run lint
        run: |
            pip install flake8
            flake8 .

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          supplychain360:
            target: dev
            outputs:
              dev:
                account: ${{ secrets.snowflake_account }}
                database: supplychain360_db
                password: ${{ secrets.snowflake_password }}
                role: supplychain360_role
                schema: staging
                threads: 4
                type: snowflake
                user: ERIC
                warehouse: supplychain360_wh
              
          EOF

      - name: Run dbt deps
        working-directory: ./dbt
        run: dbt deps

      - name: Run dbt debug
        working-directory: ./dbt
        run: dbt debug

      - name: Run dbt tests
        working-directory: ./dbt
        run: dbt test